AM.UI.Web/Models/ErrorViewModel.cs
namespace AM.UI.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AM.UI.Web/Controllers/FlightController.cs
using AM.ApplicationCore.Domain;
using AM.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AM.UI.Web.Controllers
{
    public class FlightController : Controller
    {

            private readonly IServiceFlight _flightService;
        private readonly IServicePlane _planeservice;
            public FlightController(IServiceFlight flightService ,IServicePlane planeService)
            {
                _flightService = flightService;
                _planeservice = planeService;
            }

            // GET: FlightController
            public ActionResult Index(DateTime? dateDepart)
        {
            if(dateDepart == null)
            {
                return View(_flightService.GetAll().ToList());
            }
            else
                return View(_flightService.GetMany(f=>f.flighDtae == dateDepart).ToList());
           
        }
        public ActionResult Sort()
        {
            return View("Index", _flightService.SortFlights());
        }

        // GET: FlightController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FlightController/Create
        public ActionResult Create()
        {
            ViewBag.Planes = new SelectList(_planeservice.GetAll().ToList(),"PlaneId","PlaneId");
            return View();
        }

        // POST: FlightController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Flight flight)
        {
            try
            {
                _flightService.Add(flight);
                _flightService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FlightController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FlightController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AM.UI.Web/Controllers/HomeController.cs
using AM.UI.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AM.UI.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AM.UI.Web/Controllers/PlaneController.cs
using AM.ApplicationCore.Domain;
using AM.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AM.UI.Web.Controllers
{
    public class PlaneController : Controller
    {

        private readonly IServicePlane _planeService;
        public PlaneController(IServicePlane planeService)
        {
            _planeService = planeService;
        }
        // GET: PlaneController
        public ActionResult Index()
        {
            return View( _planeService.GetAll().ToList());
        }

        // GET: PlaneController/Details/5
        public ActionResult Details(int id)
        {
            return View(_planeService.GetById(id));
        }

        // GET: PlaneController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PlaneController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Plane p )
        {
            try
            {
                    _planeService.Add(p);
                     _planeService.Commit();
                   return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaneController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_planeService.GetById(id));
        }

        // POST: PlaneController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Plane p)
        {
            try
            {
                _planeService.Update(p);
                _planeService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaneController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_planeService.GetById(id));
        }

        // POST: PlaneController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Plane p)
        {
            try
            {
                _planeService.Delete(_planeService.GetById(id));
                _planeService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AM.UI.Web/Views/Flight/Create.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="destination" class="control-label"></label>
                <input asp-for="destination" class="form-control" />
                <span asp-validation-for="destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="departure" class="control-label"></label>
                <input asp-for="departure" class="form-control" />
                <span asp-validation-for="departure" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="flighDtae" class="control-label"></label>
                <input asp-for="flighDtae" class="form-control" />
                <span asp-validation-for="flighDtae" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="effectiveArrival" class="control-label"></label>
                <input asp-for="effectiveArrival" class="form-control" />
                <span asp-validation-for="effectiveArrival" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="estimateDuration" class="control-label"></label>
                <input asp-for="estimateDuration" class="form-control" />
                <span asp-validation-for="estimateDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneId" class="control-label"></label>
                <select asp-for="PlaneId" class="form-control" asp-items="ViewBag.Planes"></select>
                <span asp-validation-for="PlaneId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Airline" class="control-label"></label>
                <input asp-for="Airline" class="form-control" />
                <span asp-validation-for="Airline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.Web/Views/Flight/Index.cshtml
@model IEnumerable<AM.ApplicationCore.Domain.Flight>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-action="index">
    <fieldset>
        <legend> Recherche</legend>
        Saisir une date de départ :
        <input type="date" name="dateDepart" />
        <input type="submit" value="Serach" />
    </fieldset>
</form>
<form asp-action="Sort">
    <fieldset>
        <input type="submit" value="Sort" />
    </fieldset>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.departure)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.flighDtae)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.flightId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.effectiveArrival)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.estimateDuration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaneId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Airline)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.departure)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.flighDtae)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.flightId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.effectiveArrival)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.estimateDuration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlaneId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Airline)
            </td>
            <td>
                @Html.ActionLink("Plane", "Details","Plane", new {  id=item.PlaneId  }) |
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

AM.UI.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AM.UI.Web/Views/Plane/Create.cshtml
@model AM.ApplicationCore.Domain.Plane

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Plane</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="capacity" class="control-label"></label>
                <input asp-for="capacity" class="form-control" />
                <span asp-validation-for="capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufactureDate" class="control-label"></label>
                <input asp-for="ManufactureDate" class="form-control" />
                <span asp-validation-for="ManufactureDate" class="text-danger"></span>
            </div>
        
            <div class="form-group">
                <label asp-for="planeType" class="control-label"></label>
                <select asp-for="planeType" class="form-control"
                 asp-items="Html.GetEnumSelectList<AM.ApplicationCore.Domain.planeType>()"></select>
                
                <span asp-validation-for="planeType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.Web/Views/Plane/Delete.cshtml
@model AM.ApplicationCore.Domain.Plane

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Plane</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufactureDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufactureDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.planeType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.planeType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AM.UI.Web/Views/Plane/Details.cshtml
@model AM.ApplicationCore.Domain.Plane

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Plane</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufactureDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufactureDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.planeType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.planeType)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

AM.UI.Web/Views/Plane/Edit.cshtml
@model AM.ApplicationCore.Domain.Plane

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Plane</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="capacity" class="control-label"></label>
                <input asp-for="capacity" class="form-control" />
                <span asp-validation-for="capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufactureDate" class="control-label"></label>
                <input asp-for="ManufactureDate" class="form-control" />
                <span asp-validation-for="ManufactureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneId" class="control-label"></label>
                <input asp-for="PlaneId" class="form-control" />
                <span asp-validation-for="PlaneId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="planeType" class="control-label"></label>
                <input asp-for="planeType" class="form-control" />
                <span asp-validation-for="planeType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.Web/Views/Plane/Index.cshtml
@model IEnumerable<AM.ApplicationCore.Domain.Plane>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.capacity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ManufactureDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaneId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.planeType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.capacity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManufactureDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlaneId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.planeType)
            </td>
            <td>
                
                @Html.ActionLink("Edit", "Edit", new {  id=item.PlaneId}) |
                @Html.ActionLink("Details", "Details", new {id = item.PlaneId  }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.PlaneId })
            </td>
        </tr>
}
    </tbody>
</table>

AM.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AM.UI.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AM.UI.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AM.UI.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flight" asp-action="Index">Flights</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plane" asp-action="Index">Planes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AM.UI.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>